function bestpeerui(){var l='',F='" for "gwt:onLoadErrorFn"',D='" for "gwt:onPropertyErrorFn"',n='"><\/script>',p='#',hb='&',r='/',jc='<script defer="defer">bestpeerui.onInjectionDone(\'bestpeerui\')<\/script>',mc='<script id="',fc='<script language="javascript" src="',A='=',q='?',C='Bad handler "',cc='DOMContentLoaded',Ab="GWT module 'bestpeerui' needs to be (re)compiled, please run a compile or use the Compile/Browse button in hosted mode",bc='GwtExt.css',o='SCRIPT',lb='Unexpected exception in locale detection, using default: ',kb='_',ib='__gwt_Locale',lc='__gwt_marker_bestpeerui',s='base',nb='begin',m='bestpeerui',cb='bootstrap',u='clear.cache.gif',z='content',jb='default',kc='end',tb='gecko',ub='gecko1_8',yb='gwt.hybrid',E='gwt:onLoadErrorFn',B='gwt:onPropertyErrorFn',y='gwt:property',ac='head',xb='hosted.html?bestpeerui',Fb='href',sb='ie6',ab='iframe',t='img',bb="javascript:''",ec='js/columntree/ColumnNodeUI.js',gc='js/columntree/ColumnNodeUI.js"><\/script>',Bb='js/columntree/column-tree.css',hc='js/yui/charts/yui-chart.js',ic='js/yui/charts/yui-chart.js"><\/script>',Cb='link',wb='loadExternalRefs',fb='locale',gb='locale=',v='meta',eb='moduleRequested',dc='moduleStartup',rb='msie',w='name',ob='opera',db='position:absolute;width:0;height:0;border:none',Db='rel',qb='safari',zb='selectingPermutation',x='startup',Eb='stylesheet',vb='unknown',mb='user.agent',pb='webkit';var oc=window,k=document,nc=oc.__gwtStatsEvent?function(a){return oc.__gwtStatsEvent(a)}:null,cd,yc,tc,sc=l,Bc={},fd=[],bd=[],rc=[],Ec,ad;nc&&nc({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:nb});if(!oc.__gwt_stylesLoaded){oc.__gwt_stylesLoaded={}}if(!oc.__gwt_scriptsLoaded){oc.__gwt_scriptsLoaded={}}function xc(){var b=false;try{b=oc.external&&(oc.external.gwtOnLoad&&oc.location.search.indexOf(yb)==-1)}catch(a){}xc=function(){return b};return b}
function Ac(){if(cd&&yc){var c=k.getElementById(m);var b=c.contentWindow;if(xc()){b.__gwt_getProperty=function(a){return uc(a)}}bestpeerui=null;b.gwtOnLoad(Ec,m,sc);nc&&nc({moduleName:m,subSystem:x,evtGroup:dc,millis:(new Date()).getTime(),type:kc})}}
function vc(){var j,h=lc,i;k.write(mc+h+n);i=k.getElementById(h);j=i&&i.previousSibling;while(j&&j.tagName!=o){j=j.previousSibling}function f(b){var a=b.lastIndexOf(p);if(a==-1){a=b.length}var c=b.indexOf(q);if(c==-1){c=b.length}var d=b.lastIndexOf(r,Math.min(c,a));return d>=0?b.substring(0,d+1):l}
;if(j&&j.src){sc=f(j.src)}if(sc==l){var e=k.getElementsByTagName(s);if(e.length>0){sc=e[e.length-1].href}else{sc=f(k.location.href)}}else if(sc.match(/^\w+:\/\//)){}else{var g=k.createElement(t);g.src=sc+u;sc=f(g.src)}if(i){i.parentNode.removeChild(i)}}
function Fc(){var f=document.getElementsByTagName(v);for(var d=0,g=f.length;d<g;++d){var e=f[d],h=e.getAttribute(w),b;if(h){if(h==y){b=e.getAttribute(z);if(b){var i,c=b.indexOf(A);if(c>=0){h=b.substring(0,c);i=b.substring(c+1)}else{h=b;i=l}Bc[h]=i}}else if(h==B){b=e.getAttribute(z);if(b){try{ad=eval(b)}catch(a){alert(C+b+D)}}}else if(h==E){b=e.getAttribute(z);if(b){try{Ec=eval(b)}catch(a){alert(C+b+F)}}}}}}
function qc(a,b){return b in fd[a]}
function pc(a){var b=Bc[a];return b==null?null:b}
function uc(d){var e=bd[d](),b=fd[d];if(e in b){return e}var a=[];for(var c in b){a[b[c]]=c}if(ad){ad(d,a,e)}throw null}
var wc;function zc(){if(!wc){wc=true;var a=k.createElement(ab);a.src=bb;a.id=m;a.style.cssText=db;a.tabIndex=-1;k.body.appendChild(a);nc&&nc({moduleName:m,subSystem:x,evtGroup:dc,millis:(new Date()).getTime(),type:eb});a.contentWindow.location.replace(sc+dd)}}
bd[fb]=function(){try{var g;if(g==null){var b=location.search;var h=b.indexOf(gb);if(h>=0){var e=b.substring(h);var c=e.indexOf(A)+1;var d=e.indexOf(hb);if(d==-1){d=e.length}g=e.substring(c,d)}}if(g==null){g=pc(fb)}if(g==null){g=oc[ib]}if(g==null){return jb}while(!qc(fb,g)){var f=g.lastIndexOf(kb);if(f==-1){g=jb;break}else{g=g.substring(0,f)}}return g}catch(a){alert(lb+a);return jb}};fd[fb]={'default':0,zh:1};bd[mb]=function(){var d=navigator.userAgent.toLowerCase();var b=function(a){return parseInt(a[1])*1000+parseInt(a[2])};if(d.indexOf(ob)!=-1){return ob}else if(d.indexOf(pb)!=-1){return qb}else if(d.indexOf(rb)!=-1){var c=/msie ([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=6000){return sb}}}else if(d.indexOf(tb)!=-1){var c=/rv:([0-9]+)\.([0-9]+)/.exec(d);if(c&&c.length==3){if(b(c)>=1008)return ub}return tb}return vb};fd[mb]={gecko:0,gecko1_8:1,ie6:2,opera:3,safari:4};bestpeerui.onScriptLoad=function(){if(wc){yc=true;Ac()}};bestpeerui.onInjectionDone=function(){cd=true;nc&&nc({moduleName:m,subSystem:x,evtGroup:wb,millis:(new Date()).getTime(),type:kc});Ac()};vc();var dd;if(xc()){if(oc.external.initModule&&oc.external.initModule(m)){oc.location.reload();return}dd=xb}Fc();nc&&nc({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:zb});if(!dd){try{alert(Ab);return}catch(a){return}}var Dc;function Cc(){if(!tc){tc=true;if(!__gwt_stylesLoaded[Bb]){var a=k.createElement(Cb);__gwt_stylesLoaded[Bb]=a;a.setAttribute(Db,Eb);a.setAttribute(Fb,sc+Bb);k.getElementsByTagName(ac)[0].appendChild(a)}if(!__gwt_stylesLoaded[bc]){var a=k.createElement(Cb);__gwt_stylesLoaded[bc]=a;a.setAttribute(Db,Eb);a.setAttribute(Fb,sc+bc);k.getElementsByTagName(ac)[0].appendChild(a)}Ac();if(k.removeEventListener){k.removeEventListener(cc,Cc,false)}if(Dc){clearInterval(Dc)}}}
if(k.addEventListener){k.addEventListener(cc,function(){zc();Cc()},false)}var Dc=setInterval(function(){if(/loaded|complete/.test(k.readyState)){zc();Cc()}},50);nc&&nc({moduleName:m,subSystem:x,evtGroup:cb,millis:(new Date()).getTime(),type:kc});nc&&nc({moduleName:m,subSystem:x,evtGroup:wb,millis:(new Date()).getTime(),type:nb});if(!__gwt_scriptsLoaded[ec]){__gwt_scriptsLoaded[ec]=true;document.write(fc+sc+gc)}if(!__gwt_scriptsLoaded[hc]){__gwt_scriptsLoaded[hc]=true;document.write(fc+sc+ic)}k.write(jc)}
bestpeerui();