package sg.edu.nus.sqlparser.java_cup_use;

//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Jul 12 15:58:40 SGT 2003
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
	/* terminals */
	public static final int ORDERBY = 19;
	public static final int WHERE = 16;
	public static final int FROM = 15;
	public static final int GROUPBY = 17;
	public static final int SELECT = 14;
	public static final int EQUAL = 11;
	public static final int SEMI = 4;
	public static final int NOTEQUAL = 12;
	public static final int LTOE = 9;
	public static final int STAR = 6;
	public static final int ID = 2;
	public static final int GTOE = 10;
	public static final int INTLIT = 21;
	public static final int COMMA = 3;
	public static final int LESSTHAN = 7;
	public static final int EOF = 0;
	public static final int STRINGLIT = 20;
	public static final int DISTINCT = 18;
	public static final int error = 1;
	public static final int DOT = 5;
	public static final int LIKE = 13;
	public static final int GREATERTHAN = 8;
}