package sg.edu.nus.ui.client.BestPeerWidgets;

public enum REPORT_ITEM {
	NUM_LOCAL_QUERIES,

	NUM_SUCCESSFULL_LOCAL_QUERIES,

	NUM_QUERIES,

	NUM_INDEX_QUERIES,

	NUM_INCOMING_MSGS,

	NUM_OUTGOING_MSGS,

	SIZE_INCOMING_MSGS,

	SIZE_OUTGOING_MSGS;

	public final static REPORT_ITEM[] itemset = {
			REPORT_ITEM.NUM_INCOMING_MSGS, REPORT_ITEM.NUM_OUTGOING_MSGS,
			REPORT_ITEM.SIZE_INCOMING_MSGS, REPORT_ITEM.SIZE_OUTGOING_MSGS,
			REPORT_ITEM.NUM_LOCAL_QUERIES,
			REPORT_ITEM.NUM_SUCCESSFULL_LOCAL_QUERIES, REPORT_ITEM.NUM_QUERIES,
			REPORT_ITEM.NUM_INDEX_QUERIES };
}